# Generated by Django 5.1.6 on 2026-09-18 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=32)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('google_sub', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('photo_url', models.URLField(blank=True)),
                ('pixels_placed', models.BigIntegerField(default=0)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_until', models.DateTimeField(blank=True, null=True)),
                ('ban_reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['last_ip'], name='canvas_play_last_ip_d42c72_idx'), models.Index(fields=['-last_seen'], name='canvas_play_last_se_4190d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.SmallIntegerField()),
                ('y', models.SmallIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('done', "Ko'rildi"), ('rejected', 'Rad etildi')], db_index=True, default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='canvas.player')),
            ],
        ),
        migrations.CreateModel(
            name='PixelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.SmallIntegerField()),
                ('y', models.SmallIntegerField()),
                ('color', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('player', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='canvas.player')),
            ],
            options={
                'indexes': [models.Index(fields=['x', 'y', '-created_at'], name='px_xy_time_idx'), models.Index(fields=['player', '-created_at'], name='px_player_idx')],
            },
        ),
    ]
