# Generated by Django 5.1.6 on 2026-09-18 20:39

import canvas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=255)),
                ('reason', models.CharField(choices=[('auto', "Jadval bo'yicha"), ('milestone', 'Bosqich'), ('manual', "Qo'lda"), ('full', "Doska to'ldi")], default='auto', max_length=12)),
                ('painted', models.IntegerField(default=0)),
                ('fill_percent', models.FloatField(default=0)),
                ('changed', models.IntegerField(default=0)),
                ('online', models.IntegerField(default=0)),
                ('bytes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='player',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited', to='canvas.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='invites_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('code', models.CharField(db_index=True, default=canvas.models.new_code, max_length=12, unique=True)),
                ('pixels_placed', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_teams', to='canvas.player')),
            ],
            options={
                'ordering': ('-pixels_placed',),
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='canvas.team'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team', '-pixels_placed'], name='canvas_play_team_id_8a8452_idx'),
        ),
    ]
