# Generated by Django 5.1.6 on 2026-09-18 20:40

import canvas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_fill_invite_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='invite_code',
            field=models.CharField(db_index=True, default=canvas.models.new_code, max_length=12, unique=True),
        ),
    ]
