# Generated by Django 5.1.6 on 2026-09-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0004_invite_code_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='invite_credited',
            field=models.BooleanField(default=False),
        ),
    ]
