# Generated by Django 5.1.6 on 2026-09-24 08:59

import canvas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0005_invite_credited'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Million Piksel', max_length=60)),
                ('seo_title', models.CharField(default='Million Piksel — 1 000 000 pikselli umumiy doska', max_length=70)),
                ('seo_description', models.CharField(default="Do'stlar bilan birga 1000×1000 umumiy doskada rasm chizing. Har bir piksel joyida qoladi. Telegram orqali kiring.", max_length=320)),
                ('seo_keywords', models.CharField(blank=True, default="million piksel, pixel art, r/place, umumiy doska, telegram o'yin", max_length=255)),
                ('seo_text', models.TextField(blank=True, help_text="Qidiruv robotlari o'qiydigan qisqa matn (saytda ko'rinmaydi).")),
                ('public_url', models.URLField(blank=True, help_text='Asosiy manzil, masalan https://millionpixel.uz')),
                ('og_image', models.CharField(blank=True, max_length=255)),
                ('favicon', models.CharField(blank=True, max_length=255)),
                ('theme_color', models.CharField(default='#1E7F86', max_length=9)),
                ('twitter', models.CharField(blank=True, max_length=40)),
                ('locale', models.CharField(default='uz', max_length=10)),
                ('robots_index', models.BooleanField(default=True)),
                ('google_verification', models.CharField(blank=True, max_length=120)),
                ('yandex_verification', models.CharField(blank=True, max_length=120)),
                ('announcement', models.CharField(blank=True, max_length=200)),
                ('announcement_on', models.BooleanField(default=False)),
                ('readonly', models.BooleanField(default=False, help_text="Faqat ko'rish rejimi: hech kim piksel qo'ya olmaydi.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=canvas.models._upload_path)),
                ('name', models.CharField(max_length=200)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('uploaded_by', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
