# Generated by Django 5.1.6 on 2026-09-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0006_site_settings_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cooldown_override',
            field=models.IntegerField(default=0, help_text='1 piksel tiklanish vaqti (soniya). 0 = onlayn soniga qarab.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='draw_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='draw_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_file',
            field=models.CharField(blank=True, help_text='Google fayl usuli: google1234abcd.html (fayl nomi)', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unlimited',
            field=models.BooleanField(default=False, help_text="Cheksiz chizish: bo'yoq sarflanmaydi."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unlimited_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unlimited_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
